modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ud_skurczybyk"
version="1.21.37"
displayName="ud_skurczybyk"
displayURL="https://mcreator.net"
credits="patron be like"
authors="kfc"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ud_skurczybyk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.ud_skurczybyk]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration